### ISSUE TITLE
Weird bug with super wrench

### ISSUE THREAD

**Issue by ghost** [PanSzelescik/coolgadgets#14]
Before I right click with the wrench
![2019-02-04_23 17 00](https://user-images.githubusercontent.com/37633323/52254371-152d1f80-28d3-11e9-8cba-aaca019771a1.png)

After I right click with wrench, This does not happen all the time but does happen to the point it needed reporting,

![2019-02-04_23 17 26](https://user-images.githubusercontent.com/37633323/52254397-368e0b80-28d3-11e9-9fe0-1e0ef0518499.png)

**Comment by PanSzelescik** [comment]
I do not know what you're talking about
https://imgur.com/cPJFf8e
I have a weak PC
